### ISSUE TITLE
raspi_alarm_clock.py failed with accentued characters in playlist name

### ISSUE THREAD

**Issue by t-chab** [StryKaizer/Raspi-alarm-clock#1]
I have a problem with a Spotify playlist named _Réveil_ (Wakeup in french). The script crash with the following error : 

```
/home/volumio/Raspi-alarm-clock/players/spop_play.py:15: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if (playlist['name'] == settings.get('Music', 'SPOTIFY_PLAYLIST')):
Traceback (most recent call last):
  File "/home/volumio/Raspi-alarm-clock/raspi_alarm_clock.py", line 130, in <module>
    main()
  File "/home/volumio/Raspi-alarm-clock/raspi_alarm_clock.py", line 98, in main
    spop_play.play_music(settings)
  File "/home/volumio/Raspi-alarm-clock/players/spop_play.py", line 32, in play_music
    tn.write("play " + str(playlist_index) + "\n")
UnboundLocalError: local variable 'playlist_index' referenced before assignment
```

and playback doesn't start.

How can I fix this ?

Thanks.

**Comment by StryKaizer** [comment]
Thanks for reporting!
Fixed in https://github.com/StryKaizer/Raspi-alarm-clock/commit/4f9b56e006bc9120f9a38e5d2fee96750ff9b289

**Comment by t-chab** [comment]
And thanks a lot to you for the quick fix :+1:
